// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCLE2ufgBdie7atdwCqp16zuDnhNFE7w',
    appId: '1:84276250442:web:0f7ff22d4f87a76c65e3b3',
    messagingSenderId: '84276250442',
    projectId: 'pensiondatabase',
    authDomain: 'pensiondatabase.firebaseapp.com',
    storageBucket: 'pensiondatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OaquN7oGz37ZQsWxtD3354REPpQEqq8',
    appId: '1:84276250442:android:f029f56358ca7d6465e3b3',
    messagingSenderId: '84276250442',
    projectId: 'pensiondatabase',
    storageBucket: 'pensiondatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIECZw2gMa7f5WIuYH0KGvK5ElNmFcZl8',
    appId: '1:84276250442:ios:ec1193b2fc29c66665e3b3',
    messagingSenderId: '84276250442',
    projectId: 'pensiondatabase',
    storageBucket: 'pensiondatabase.appspot.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIECZw2gMa7f5WIuYH0KGvK5ElNmFcZl8',
    appId: '1:84276250442:ios:5ba1abd018d56e8a65e3b3',
    messagingSenderId: '84276250442',
    projectId: 'pensiondatabase',
    storageBucket: 'pensiondatabase.appspot.com',
    iosBundleId: 'com.example.finalYearProject.RunnerTests',
  );
}
